FROM maven:3.8.7-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/cnpj-analyzer-1.0-SNAPSHOT.jar app.jar

# Criar diretório para dados
RUN mkdir -p data/processed

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]